module.exports = {
 FastFood : 'Combo meal in fast food restaurant (Big Mac Meal or similar)',
 BasicLunchMenu : 'Basic lunchtime menu (including a drink) in the business district',
 Chicken500gr : '500 gr (1 lb.) of boneless chicken breast',
 Milk1L : '1 liter (1 qt.) of whole fat milk',
 Eggs12 : '12 eggs, large',
 Tomato1kg : '1 kg (2 lb.) of tomatoes',
 Cheese500gr : '500 gr (16 oz.) of local cheese',
 Apples1kg : '1 kg (2 lb.) of apples',
 Potatos1kg : '1 kg (2 lb.) of potatoes',
 BeerHalfLInSupermarket : '0.5 l (16 oz) domestic beer in the supermarket',
 WineRedGoodQuality : '1 bottle of red table wine, good quality',
 CocaCola2L : '2 liters of Coca-Cola',
 BreadSupermarket : 'Bread for 2 people for 1 day',   
}